# Generated by Django 5.1.3 on 2024-11-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('player_id', models.UUIDField(primary_key=True, serialize=False)),
                ('credential', models.CharField(max_length=50)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('last_session', models.DateTimeField()),
                ('total_spend', models.FloatField()),
                ('total_refund', models.FloatField()),
                ('total_transactions', models.IntegerField()),
                ('last_purchase', models.DateTimeField()),
                ('active_campaigns', models.JSONField(default=list)),
                ('devices', models.JSONField(default=list)),
                ('level', models.IntegerField()),
                ('xp', models.IntegerField()),
                ('total_playtime', models.FloatField()),
                ('country', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
                ('birthdate', models.DateTimeField()),
                ('gender', models.CharField(max_length=10)),
                ('inventory', models.JSONField(default=dict)),
                ('clan', models.JSONField(default=dict)),
                ('custom_field', models.CharField(max_length=50)),
            ],
        ),
    ]
